apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: backend
  strategy: {}
  template:
    metadata:
      labels:
        io.network/react-spring: "true"
        io.network/spring-mysql: "true"
        io.service: backend
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_ROOT_PASSWORD
              value: db-57xsl
          image: piyushrgupta/backend:v1.2
          name: backend
          command: ["java","-cp","app:app/lib/*","com.company.project.Application"]
          resources: {}
      restartPolicy: Always