apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.network/spring-mysql: "true"
        io.service: db
    spec:
      serviceAccountName: default
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                 configMapKeyRef:
                  name: databaseconfig
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: dbpassword
                 key:  db-password
          image: mysql:8.0.19
          name: db
          resources:
            requests:
              memory: "800Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port : 3306
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
                - --silent
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          emptyDir: {}
