apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.network/react-spring: "true"
        io.service: frontend
    spec:
      containers:
        - image: piyushrgupta/frontend:v6.0
          name: frontend
          ports:
            - containerPort: 3000
