apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.service: db-data
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
