kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-access
spec:
  podSelector:
    matchLabels:
      io.service: backend
  ingress:
    - from:
      - podSelector:
          matchLabels:
            io.service: frontend
      ports:
        - protocol: TCP
          port: 8080