kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: mysqlaccess
spec:
  podSelector:
    matchLabels:
      io.service: db
  ingress:
    - from:
      - podSelector:
          matchLabels:
            io.service: backend
      ports:
        - protocol: TCP
          port: 3306