apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: frontendport
      port: 80
      targetPort: 3000
  selector:
    io.service: frontend
